a=5
b=3.14
c="Hello"
x=True
y={"name":"maha","age":19}
z=("apple","orrange","banana")
h=["tomato","carrot","cucumber"]
print(type(a))
print(type(b))
print(type(c))
print(type(x))
print(type(y))
print(type(z))
print(type(h))
